before_install:
- "sudo apt-get update && sudo apt-get install --no-install-recommends graphviz"
script:
- mkdir _build
- dot -Tpdf tasks.gv -o _build/tasks.pdf
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 85b8c5d9cc84d19be1eb453a0e41deb708f8d027
  keep_history: true
  on:
    branch: master



