before_install:
- "sudo apt-get update && sudo apt-get install --no-install-recommends graphviz"
script:
- mkdir _build
- dot -Tpdf tasks.gv -o _build/tasks.pdf

after_success:
 - /bin/sh .travis/push.sh
